services:
  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./storage:/app/storage
  mongodb:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: python_learning_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mongodb_compass:
    image: haohanyang/compass-web
    ports:
      - "8080:8080"
    environment:
      - CW_MONGO_URI=mongodb://mongodb:27017
volumes:
  mongodb_data:
